Stop using the beta.kubernetes.io/arch
openshift/whereabouts-cni pull request #106
Opened 2022-12-07 05:40 UTC by pacoxu

Use kubernetes.io/arch instead

2022-12-07 08:26 UTC, maiqueb requested changes
I think this change must first happen in https://github.com/k8snetworkplumbingwg/whereabouts/blob/master/doc/crds/daemonset-install.yaml, and only then be backported to this repo.

2022-12-07 10:51 UTC, pacoxu commented
waiting for https://github.com/k8snetworkplumbingwg/whereabouts/pull/287

2022-12-07 10:55 UTC, maiqueb approved these changes
Thanks.

2022-12-07 10:56 UTC, maiqueb commented
/lgtm

2022-12-07 12:22 UTC, maiqueb commented
/hold
let's wait for @dougbtv 's oppinion on this first.

2023-03-08 09:25 UTC, pacoxu commented
@dougbtv 
/remove-lifecycle stale

2023-06-07 14:12 UTC, dougbtv commented
Please file this upstream @ https://github.com/k8snetworkplumbingwg/whereabouts -- thank you!

2023-06-07 14:12 UTC, closed without merging